package:
  name: manset
  version: 1.0.0

source:
  path: ../

build:
  number: 1
  script: script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - manset = manset.__init__:manset_gui

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - numpy
    - matplotlib
    - pypdf2
    - reportlab
    - psutil
    - numba

about:
  summary: Graphical User Interface implementation of the Mandelbrot set for easy navigation around the border of convergence for two given ranges of values in the complex plane.

extra:
  recipe-maintainers:
    -mateisarivan