package:
  name: manset
  version: 0.1

source:
  path: ../

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - numpy
    - matplotlib

  entry_points:
    - manset = manset.__init__:manset_gui

about:
  summary: Graphical User Interface implementation of the Mandelbrot set for easy navigation around the border of convergence for two given ranges of values in the complex plane.

extra:
  recipe-maintainers:
    -mateisarivan